# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "devoir 2: l√©gendes urbaines (Jailbreak IA)"


prompts:
  - file://prompt.json


providers:
  - id: openrouter:openai/gpt-3.5-turbo


tests:
  - vars:
      articles: file://articles.txt



  