# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "devoir 1: themes technique autour des llms ( cas openclaw )"


prompts:
  - file://structure.txt
  - file://articles.txt
  - |
    Tu es un expert en architectures LLM et en systèmes multi-agents. 
    À partir exclusivement des sources ci-dessus et en respectant strictement la structure imposée, rédige une note de synthèse académique complète (1200 à 1500 mots) sur OpenClaw en tant que framework d'agents LLM..

    Contraintes :
    - Utiliser uniquement les informations issues des sources
    - Citer les sources sous la forme [ARTICLE X]
    - Mentionner explicitement toute incertitude
    - Comparer avec une architecture LLM simple
    - Minimum 1200 mots


providers:
  - id: openrouter:openai/gpt-3.5-turbo



  